# Overview

이 과정에서는 예측함수를 가설함수라 칭할 것이다.

실제값과 가설함수의 차이

![](2021-12-08-23-45-13.png)

Cost function이라고 부를 예정

![](2021-12-08-23-45-36.png)

Cost function을 최소화 할 수 있는 weight 값 세타를 구한다.

![](2021-12-08-23-46-12.png)

미분을 통해 구할 수 있다.

weights의 최적값 컴퓨터가 찾는 방법
- 연립방적식 풀기 (normal equation)
- gradient descent

# Normal equation
Cost Function을 최소화하는 방법

![](2021-12-08-23-53-32.png)

![](2021-12-08-23-53-44.png)


![](2021-12-08-23-54-14.png)
![](2021-12-08-23-54-25.png)
![](2021-12-08-23-54-38.png)
![](2021-12-08-23-54-53.png)
![](2021-12-08-23-55-04.png)
![](2021-12-08-23-55-15.png)
![](2021-12-08-23-55-24.png)
![](2021-12-08-23-55-32.png)
![](2021-12-08-23-55-46.png)

# Normal equation 실습

In [12]:
from normal_equation_lr import LinearRegression
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./data/test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [3]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

## Build Model

In [14]:
import normal_equation_lr as linear_model
import imp
imp.reload(linear_model)

<module 'normal_equation_lr' from 'c:\\Users\\jcw74\\Desktop\\git\\Study-1\\BoostCourse\\[부스트코스] 머신러닝을 위한 파이썬\\4_Linear Regression\\normal_equation_lr.py'>

In [15]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [16]:
lr.fit(X, y)

In [17]:
lr.intercept

-0.46181077366112167

In [18]:
lr.coef

array([1.01433536])

In [19]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

## Validation
scikit learn의 linear regression 모델과 비교

In [20]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X, y)

LinearRegression()

In [21]:
sk_lr.intercept_

-0.4618107736611563

In [22]:
sk_lr.coef_

array([1.01433536])

In [24]:
np.isclose(lr.coef, sk_lr.coef_)

array([ True])

In [27]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [26]:
sk_lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

## LOAD DATASET - multiple variables

In [28]:
df = pd.read_csv("./data/mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [29]:
y = df["average_points_scored"].values

In [30]:
df.iloc[:,:-1].head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [31]:
X = df.iloc[:,:-1].values
X[:5]

array([[  6.8  , 225.   ,   0.442,   0.672],
       [  6.3  , 180.   ,   0.435,   0.797],
       [  6.4  , 190.   ,   0.456,   0.761],
       [  6.2  , 180.   ,   0.416,   0.651],
       [  6.9  , 205.   ,   0.449,   0.9  ]])

### Rescaled

In [33]:
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

rescaled_X = (X - mu_X) / std_X
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

### Validation

In [34]:
lr.fit(rescaled_X, y)

In [35]:
lr.coef

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [36]:
lr.intercept

11.79074074074074

In [37]:
sk_lr.fit(rescaled_X, y)

LinearRegression()

In [38]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [39]:
sk_lr.intercept_

11.790740740740736