# Learning Rate

In [1]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [2]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [3]:
# try different learning_rate
# learning_rate = 65535  # ? it works too hahaha
learning_rate = 0.1
# learning_rate = 1e-10  # small learning rate won't work either

In [4]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=3, input_dim=3, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=learning_rate), metrics=['accuracy'])

C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [5]:
tf.model.fit(x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 219ms/step - loss: 2.3342 - accuracy: 0.3750
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 2.0346 - accuracy: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.7421 - accuracy: 0.2500
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.4677 - accuracy: 0.3750
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2327 - accuracy: 0.2500
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.0856 - accuracy: 0.3750
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0397 - accuracy: 0.2500
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0270 - accuracy: 0.3750
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0157 - accuracy: 0.2500
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0063 - accuracy: 0.5000
Epoch 11/1000
1/1

In [7]:
# predict
print("Prediction: ", tf.model.predict(x_test).argmax(axis = -1))

Prediction:  [2 2 2]


In [8]:
# Calculate the accuracy
print("Accuracy: ", tf.model.evaluate(x_test, y_test)[1])

1/1 [==============================] - 0s 111ms/step - loss: 0.0016 - accuracy: 1.0000
Accuracy:  1.0


# Non-Normalized inputs

In [10]:
import tensorflow as tf
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [11]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [12]:
# loss가 증가하게 된다.
history = tf.model.fit(x_data, y_data, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 231ms/step - loss: 701588242432.0000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 770821181887249436691660800.0000
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: inf
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: inf
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: inf
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: inf
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: nan
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 13/100
1/1 [==============================] - 

In [13]:
print(history.history['loss']) # loss == nan

[701588242432.0, 7.708211818872494e+26, inf, inf, inf, inf, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


# Normalized inputs

In [14]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [16]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [17]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [18]:
history = tf.model.fit(x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 135ms/step - loss: 0.3562
Epoch 2/1000
1/1 [==============================] - 0s 978us/step - loss: 0.3562
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3562
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3562
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3561
Epoch 6/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3561
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3561
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3561
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3561
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3561
Epoch 11/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3560
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3560
Epoch 13/1000
1/1 [==========================

In [19]:
predictions = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

print('Prediction: \n', predictions)
print('Cost: ', score)

1/1 [==============================] - 0s 47ms/step - loss: 0.3401
Prediction: 
 [[-0.25229546]
 [ 0.61510885]
 [ 0.24229684]
 [-0.13637325]
 [-0.00152943]
 [ 0.11343475]
 [-0.02717716]
 [ 0.47558227]]
Cost:  0.34014225006103516
