# Softmax Regression

In [1]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [2]:
x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

In [3]:
x_data

array([[1., 2., 1., 1.],
       [2., 1., 3., 2.],
       [3., 1., 3., 4.],
       [4., 1., 5., 5.],
       [1., 7., 5., 5.],
       [1., 2., 5., 6.],
       [1., 6., 6., 6.],
       [1., 7., 7., 7.]], dtype=float32)

In [4]:
y_data

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [6]:
nb_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  # use_bias is True, by default

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [7]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 231ms/step - loss: 3.1797 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8689 - accuracy: 0.3750
Epoch 3/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1106 - accuracy: 0.6250
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.0246 - accuracy: 0.6250
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.9671 - accuracy: 0.6250
Epoch 6/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.9176 - accuracy: 0.6250
Epoch 7/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.8758 - accuracy: 0.6250
Epoch 8/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.8410 - accuracy: 0.6250
Epoch 9/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.8124 - accuracy: 0.7500
Epoch 10/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.7891 - accuracy: 0.7500
Epoch 11/2000
1/1

In [22]:
print('--------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis = 1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis = 1)))

print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = c_onehot.argmax(axis = -1)
print(c, c_onehot)

print('--------------')
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = all_onehot.argmax(axis = -1)
print(all, all_onehot)

--------------
[[3.5719462e-03 9.9641943e-01 8.6754335e-06]] [1]
--------------
[[0.88421243 0.10581315 0.00997445]] [0]
--------------
[[1.1784485e-08 3.2500364e-04 9.9967504e-01]] [2]
--------------
[[3.5719462e-03 9.9641943e-01 8.6754171e-06]
 [8.8421232e-01 1.0581318e-01 9.9744480e-03]
 [1.1784485e-08 3.2500364e-04 9.9967504e-01]] [1 0 2]


## Fancy Softmax Classifier

- cross_entrypy
- one_hot
- reshape

In [24]:
import tensorflow as tf
import numpy as np

# Predicting animal type based on various features
xy = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [25]:
nb_classes = 7  # 0 ~ 6

# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [26]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units = nb_classes, input_dim = 16, activation = 'softmax'))
tf.model.compile(loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.SGD(lr=0.1), metrics = ['accuracy'])
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [27]:
history = tf.model.fit(x_data, y_one_hot, epochs = 2000)

Epoch 1/2000
4/4 [==============================] - 0s 652us/step - loss: 2.3213 - accuracy: 0.1386
Epoch 2/2000
4/4 [==============================] - 0s 977us/step - loss: 1.5840 - accuracy: 0.4653
Epoch 3/2000
4/4 [==============================] - 0s 977us/step - loss: 1.3760 - accuracy: 0.5545
Epoch 4/2000
4/4 [==============================] - 0s 651us/step - loss: 1.2308 - accuracy: 0.6436
Epoch 5/2000
4/4 [==============================] - 0s 977us/step - loss: 1.1207 - accuracy: 0.7822
Epoch 6/2000
4/4 [==============================] - 0s 977us/step - loss: 1.0372 - accuracy: 0.7624
Epoch 7/2000
4/4 [==============================] - 0s 977us/step - loss: 0.9497 - accuracy: 0.7822
Epoch 8/2000
4/4 [==============================] - 0s 1ms/step - loss: 0.8954 - accuracy: 0.7822
Epoch 9/2000
4/4 [==============================] - 0s 2ms/step - loss: 0.8301 - accuracy: 0.7921
Epoch 10/2000
4/4 [==============================] - 0s 1ms/step - loss: 0.7894 - accuracy: 0.8515
Epoch

In [29]:
# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) 
# expected prediction == 3 (feathers)
print(tf.model.predict(test_data), tf.model.predict(test_data).argmax(axis = -1))

[[2.8508040e-04 4.2145353e-04 3.4697128e-03 9.9320388e-01 2.1132720e-03
  3.9881314e-08 5.0654862e-04]] [3]


In [31]:
# Full x_data test
pred = tf.model.predict(x_data).argmax(axis = -1)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P