# n_size_ndarray_creation
- 함수목적
    - n의 제곱수로 2 dimentional array를 생성하는 ndarray.
- Args
    - n: 생성하고자 하는 ndarray의 row와 column의 개수
    - dtype: 생성하려는 ndarray의 data type (np.int)
- Returns
    - row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [7]:
import numpy as np

def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange((n ** 2), dtype = dtype).reshape(n, n)
    return X

n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# zero_or_one_or_empty_ndarray
- 함수목적
shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.
Args
shape: 생성할려는 ndarray의 shape
type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
dtype: 생성하려는 ndarray의 data type (np.int)
Returns
shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨
Examples

In [9]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0 :
        X = np.zeros(shape = shape, dtype = dtype)
    elif type == 1 :
        X = np.ones(shape = shape, dtype = dtype)
    else :
        X = np.empty(shape = shape, dtype = dtype)
    return X

print(zero_or_one_or_empty_ndarray(shape=(2,2), type=1))
print(zero_or_one_or_empty_ndarray(shape=(3,3), type=99))

[[1 1]
 [1 1]]
[[         1          0          1]
 [         0          0          0]
 [         0          0 1947327091]]
