# Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준

- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원
- 선형대수와 관련된 다양한 기능 제공

$$ 2x_1 + 2x_2 + x_3 = 9 $$
$$ 2x_1 - x_2 + 2x_3 = 6 $$
$$ x_1 - x_2 + 2x_3 = 5 $$

## 코드로 방정식 표현하기
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]

constant_vector = [9, 6, 5]

- 다양한 Matrix 계산을 어떻게 활용할 것인가
- 굉장히 큰 Matrix에 대한 표현
- 처리 속도 문제 - python은 interpreter 언어

# ndarray
![](2021-11-16-09-03-42.png)
![](2021-11-16-09-04-21.png)

In [1]:
import numpy as np

test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])
# numpy는 np.array 함수를 활용 배열을 생성
# numpy는 '하나의 데이터 type'만 배열에 넣을 수 있음
# List와 가장 큰 차이점 -> dynamic typing not supported
# C의 Array를 사용하여 배열을 생성함

[1. 4. 5. 8.]


numpy.float64

In [3]:
# array creation
# shape : numpy array의 dimension 구성을 반환함
# dtype : numpy array의 데이터 type을 반환함
test_array = np.array([1, 4, 5, "8"], float)    # string type의 데이터를 입력해도
print(test_array)
print(type(test_array[3]))  # Float type으로 자동 형 변환 실시
print(test_array.dtype)     # Array 전체의 데이터 Type을 반환
print(test_array.shape)     # Array의 shape를 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [5]:
# matrix
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [6]:
# tensor
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor, int).shape

(4, 3, 4)

# Handling shape

In [7]:
# reshape : Array의 shape의 크기를 변경함. element 갯수는 동일
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
print(np.array(test_matrix).shape)  # 기존 shape
print(np.array(test_matrix).reshape(8,))    # shape의 크기 변경
print(np.array(test_matrix).reshape(8,).shape)  # 변경된 shape

(2, 4)
[1 2 3 4 1 2 5 8]
(8,)


In [9]:
# flatten : 다차원 array를 1차원 array로 변환
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# indexing & slicing

In [10]:
# indexting for numpy array
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(test_example[0][0])
print(test_example[0, 0])

1
1


In [13]:
test_example[0, 0] = 12     # matrix 0, 0에 12 할당
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [ ]:
# slicing for numpy array
test_example = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_example[ : 2, :]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

# creation function

In [16]:
# arange - array의 범위를 지정하여, 값의 list를 생성하는 명령어
np.arange(30)   # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
np.arange(0, 5, 0.5)    # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
# ones, zeros and empty
np.zeros(shape = (10, ), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [20]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# ones
print(np.ones(shape = (10, )))
print(np.ones((2, 5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# empty - shape만 주어지고 비어있는 ndarray 생성 (memory initialization이 되지 않음)
print(np.empty(shape = (10, ), dtype = np.int8))
print(np.empty((3, 5)))

[ 64 -32  75 -93   0   2   0   0   0   0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
# something_like - 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [30]:
# identity - 단위행렬(i 행렬)을 생성함
np.identity(n = 3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# eye - 대각선이 1인 행렬, k 값의 시작 index의 변경이 가능
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3, 5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(3, 5, dtype = np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [35]:
# diag - 대각 행렬의 값을 추출함
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])