# Matrix
- 행렬은 벡터를 원소로 가지는 2차원 배열이다.
- 행렬은 행과 열이라는 인덱스를 가진다.
- 행렬의 특정 행(열)을 고정하면 행(열)벡터라고 부른다.
- 벡터가 공간에서 한 점을 의미한다면 행렬은 여러 점들을 나타낸다.

In [5]:
# 행렬 곱셈 - 행렬 곱셈은 i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬을 계산한다.
import numpy as np
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

# numpy에선 @ 연산을 사용한다
x @ y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [7]:
# 행렬의 내적
# np.inner - i번째 행벡터와 j번째 행벡터 사이의 내적을 성분으로 가지는 행렬을 계산
# 수학에서 말하는 내적과 다르다.
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1, -1], 
              [1, -1, 0]])
              
np.inner(x, y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

## 행렬을 이해하는 방법
- 행렬은 벡터공간에서 사용되는 연산자로 이해한다.
- 행렬곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있다.
- 행렬곱을 통해 패턴을 추출할 수 있고 데이터를 압축할 수도 있다.


In [14]:
# 역행렬
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

print('행렬 x의 역행렬\n', np.linalg.inv(x))
print('행렬 x의 역행렬과 행렬 x의 곱\n', x @ np.linalg.inv(x))
print('행렬 x의 역행렬과 행렬 x의 곱(깔끔하게)\n', np.round(x @ np.linalg.inv(x)))

행렬 x의 역행렬
 [[ 0.21276596  0.0212766  -0.31914894]
 [-0.29787234  0.17021277  0.44680851]
 [ 0.06382979  0.10638298  0.40425532]]
행렬 x의 역행렬과 행렬 x의 곱
 [[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]
행렬 x의 역행렬과 행렬 x의 곱(깔끔하게)
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [-0.  0.  1.]]


In [ ]:
# 행렬의 역행렬을 이용한 계산은 선형회귀식을 찾는것에 도움이 된다.
# Scikit learn을 활용한 회귀분석
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x, y)
y_test = model.predict(x_test)

# 역행렬
beta = np.linalg.pinv(x) @ y
y_test = np.append(x_test) @ beta